export { HeroCarousel } from "./hero-carousel"
export { OnTrendPicks } from "./on-trend-picks"
export { NewArrivals } from "./new-arrivals"
export { BestSellers } from "./best-sellers"
export { NewsletterSection } from "./newsletter-section"
export { InstagramFeed } from "./instagram-feed"
export { CategoryTabs } from "./category-tabs"
